#!/usr/bin/env bash

EXPECTED_ARGS=1
E_BADARGS=65

if [ $# -gt $EXPECTED_ARGS ] || [ "$1" = "-h" ]
then
  echo "Usage: `basename $0` [-h] [PACKAGE_NAME]"
  if [ $# -gt $EXPECTED_ARGS ] 
  then
    exit $E_BADARGS
  else 
    exit 0
  fi
fi


if [ $# -eq 1 ]
then
  rm -f `rospack find $1`/CATKIN_IGNORE
else 
  rm -f CATKIN_IGNORE
fi

